### ISSUE TITLE
Ежесуточный отчет на email

### ISSUE THREAD

**Issue by dapi** [bitzlato/liza#16]
таблица со следующими строками:

* рынок
* количество зарегистрированных
* количество торгов
* сумма ввода вывода

**Comment by dapi** [comment]
Емайл передаются списком через запятую в переменную окружения

**Comment by dapi** [comment]
Надо исключать сделки по нашим ботам. Выводить их отдельной колонкой.
Список UID-ов будут через запятую в переменной `STATS_EXCLUDE_MEMBER_UIDS`

**Comment by Nitr** [comment]
<img width="648" alt="Screenshot 2021-11-11 at 12 48 55" src="https://user-images.githubusercontent.com/1279955/141276813-d160444e-8503-4cfe-b09f-8890cbf3800d.png">
